# <center>Laboratorium 2<br>Metod Numerycznych</center>

Instrukcja:  
Na zajęciach należy wykonać poniższe zadania, a następnie sporządzić sprawozdanie zawierające odpowiedzi (w postaci kodu) z  komentarzami w środowisku [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/) i umieścić je na platformie e-learningowej.

***Biblioteki niezbędne do wykonania zadania***:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [1]:
import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [2]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


W trakcie rozwiązywania zadań zajdzie również potrzeba mnożenia odpowiednich wektorów i macierzy ze sobą. Warto pamiętać kilka *[zasad](https://pl.wikipedia.org/wiki/Mno%C5%BCenie_macierzy)* związanych z tą czynnością. 

***Zadanie 1.***  
Napisać funkcję $fib(n)$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*.

<a id='zad1'></a>
***Zadanie 2.***   
Napisać funkcję $custom\_matrix(m, n)$, gdzie parametry m, n określają wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*. Wypełnienie macierzy można wykonać stosując pętle **for**.

In [3]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


***Zadanie 3.***  
Zrealizować funkcję $hilbert(n)$ zwracającą wypełnioną *[macierz Hilberta](http://pl.wikipedia.org/wiki/Macierz_Hilberta)* o rozmiarze n. 

***Wskazówki:*** Wiele znanych typów macierzy posiada swoją *[implementacje](https://docs.scipy.org/doc/scipy-0.16.1/reference/linalg.html#special-matrices)* w pakiecie NumPy i Scipy.

***Zadanie 4.***
Zrealizować funkcje: $upper(M)$, $lower(M)$, $diagonal(M)$, które z podanej jako argument macierzy
M będą "wyciągały" macierze odpowiednio: poddiagonalną, naddiagonalną i diagonalną. Przetestować działąnie na dowolnej macierzy.

***Zadanie 5.***  
Zadeklarować macierz M o dowolnych rozmiarach ($>2$), wypełnioną psudolosowymi wartościami. Następnie wypisać wartość najmniejszego elementu, największego elementu oraz średnią wartość wszystkich elementów. 

Ponadto wypisać te wartości również we wszystkich wierszach i kolumnach macierzy M.
  
***Wskazówki:*** Do inicjalizacji macierzy można użyć funkcji z modułu *[np.random](https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html)* np. 
*[randint](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html#numpy.random.randint)*.
Pakiet Numpy posiada także wbudowane funkcje 
*[np.amin](https://docs.scipy.org/doc/numpy/reference/generated/numpy.amin.html)*,
*[np.amax](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.amax.html#numpy.amax)* oraz
*[np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html)*.
Dodatkowo macierze typu ndarray posiadają metody
*[min()](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.min.html)* i
*[max()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.max.html)*

***Zadanie 6.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

***Zadanie 7.***
Zainicjalizować macierz $m_1$:

$m_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3m_1$
- $3m_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $m_1^T$
- $m_1 \circ v_1$ 
- $v_2^T \circ m_1$

***Zadanie 8.***
Rozwiązać układ równań:

$\begin{bmatrix}1&3&2\\-1&2&3\\8&2&-3\end{bmatrix} \begin{bmatrix}x\\y\\z\end{bmatrix} = \begin{bmatrix}7\\-2\\28\end{bmatrix} $

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)